package com.iqoo.wellness.engine.food

import com.iqoo.wellness.engine.storage.FoodEntity

object FoodSeedDatabase {
    val SEED_FOODS: List<FoodEntity> = listOf(
        FoodEntity(
            foodId = "biryani_01",
            name = "Biryani",
            category = "Rice Dishes",
            servingUnit = "plate",
            defaultGrams = 250.0,
            caloriesPer100g = 165.0,
            proteinPer100g = 7.5,
            carbsPer100g = 24.0,
            fatPer100g = 4.5,
            fiberPer100g = 1.2
        ),
        FoodEntity(
            foodId = "dosa_01",
            name = "Dosa",
            category = "South Indian",
            servingUnit = "piece",
            defaultGrams = 150.0,
            caloriesPer100g = 168.0,
            proteinPer100g = 3.9,
            carbsPer100g = 29.0,
            fatPer100g = 3.7,
            fiberPer100g = 1.4
        ),
        FoodEntity(
            foodId = "paneer_tikka_01",
            name = "Paneer Tikka",
            category = "Starters",
            servingUnit = "portion",
            defaultGrams = 180.0,
            caloriesPer100g = 240.0,
            proteinPer100g = 14.0,
            carbsPer100g = 6.0,
            fatPer100g = 18.0,
            fiberPer100g = 1.0
        ),
        FoodEntity(
            foodId = "roti_01",
            name = "Roti",
            category = "Breads",
            servingUnit = "piece",
            defaultGrams = 40.0,
            caloriesPer100g = 264.0,
            proteinPer100g = 9.0,
            carbsPer100g = 55.0,
            fatPer100g = 3.0,
            fiberPer100g = 9.0
        ),
        FoodEntity(
            foodId = "dal_tadka_01",
            name = "Dal Tadka",
            category = "Lentils",
            servingUnit = "bowl",
            defaultGrams = 200.0,
            caloriesPer100g = 110.0,
            proteinPer100g = 6.0,
            carbsPer100g = 14.0,
            fatPer100g = 3.5,
            fiberPer100g = 4.0
        ),
        FoodEntity(
            foodId = "chicken_curry_01",
            name = "Chicken Curry",
            category = "Main Course",
            servingUnit = "bowl",
            defaultGrams = 220.0,
            caloriesPer100g = 145.0,
            proteinPer100g = 16.0,
            carbsPer100g = 4.0,
            fatPer100g = 7.5,
            fiberPer100g = 1.0
        ),
        FoodEntity(
            foodId = "salad_01",
            name = "Green Salad",
            category = "Salads",
            servingUnit = "bowl",
            defaultGrams = 150.0,
            caloriesPer100g = 35.0,
            proteinPer100g = 1.5,
            carbsPer100g = 7.0,
            fatPer100g = 0.5,
            fiberPer100g = 2.5
        ),
        FoodEntity(
            foodId = "aloo_gobi",
            name = "Aloo Gobi",
            category = "Curry",
            servingUnit = "bowl",
            defaultGrams = 200.0,
            caloriesPer100g = 120.0,
            proteinPer100g = 3.0,
            carbsPer100g = 12.0,
            fatPer100g = 6.0,
            fiberPer100g = 3.2
        ),
        FoodEntity(
            foodId = "aloo_tikki",
            name = "Aloo Tikki",
            category = "Snacks",
            servingUnit = "piece",
            defaultGrams = 80.0,
            caloriesPer100g = 210.0,
            proteinPer100g = 4.0,
            carbsPer100g = 28.0,
            fatPer100g = 9.0,
            fiberPer100g = 2.5
        ),
        FoodEntity(
            foodId = "butter_chicken",
            name = "Butter Chicken",
            category = "Non-Veg",
            servingUnit = "bowl",
            defaultGrams = 250.0,
            caloriesPer100g = 180.0,
            proteinPer100g = 15.0,
            carbsPer100g = 4.5,
            fatPer100g = 11.5,
            fiberPer100g = 1.0
        ),
        FoodEntity(
            foodId = "chana_masala",
            name = "Chana Masala",
            category = "Lentils",
            servingUnit = "bowl",
            defaultGrams = 220.0,
            caloriesPer100g = 135.0,
            proteinPer100g = 7.0,
            carbsPer100g = 18.0,
            fatPer100g = 4.0,
            fiberPer100g = 5.0
        ),
        FoodEntity(
            foodId = "chapati",
            name = "Chapati",
            category = "Breads",
            servingUnit = "piece",
            defaultGrams = 40.0,
            caloriesPer100g = 264.0,
            proteinPer100g = 9.0,
            carbsPer100g = 55.0,
            fatPer100g = 3.0,
            fiberPer100g = 9.0
        ),
        FoodEntity(
            foodId = "dal_makhani",
            name = "Dal Makhani",
            category = "Lentils",
            servingUnit = "bowl",
            defaultGrams = 200.0,
            caloriesPer100g = 145.0,
            proteinPer100g = 6.5,
            carbsPer100g = 16.0,
            fatPer100g = 6.5,
            fiberPer100g = 4.5
        ),
        FoodEntity(
            foodId = "gulab_jamun",
            name = "Gulab Jamun",
            category = "Sweets",
            servingUnit = "piece",
            defaultGrams = 60.0,
            caloriesPer100g = 300.0,
            proteinPer100g = 4.5,
            carbsPer100g = 48.0,
            fatPer100g = 10.0,
            fiberPer100g = 0.5
        ),
        FoodEntity(
            foodId = "jalebi",
            name = "Jalebi",
            category = "Sweets",
            servingUnit = "piece",
            defaultGrams = 50.0,
            caloriesPer100g = 350.0,
            proteinPer100g = 2.0,
            carbsPer100g = 65.0,
            fatPer100g = 9.0,
            fiberPer100g = 0.2
        ),
        FoodEntity(
            foodId = "lassi",
            name = "Lassi",
            category = "Beverages",
            servingUnit = "glass",
            defaultGrams = 250.0,
            caloriesPer100g = 85.0,
            proteinPer100g = 3.2,
            carbsPer100g = 12.0,
            fatPer100g = 2.5,
            fiberPer100g = 0.0
        ),
        FoodEntity(
            foodId = "naan",
            name = "Naan",
            category = "Breads",
            servingUnit = "piece",
            defaultGrams = 90.0,
            caloriesPer100g = 275.0,
            proteinPer100g = 8.5,
            carbsPer100g = 52.0,
            fatPer100g = 3.5,
            fiberPer100g = 2.0
        ),
        FoodEntity(
            foodId = "palak_paneer",
            name = "Palak Paneer",
            category = "Curry",
            servingUnit = "bowl",
            defaultGrams = 220.0,
            caloriesPer100g = 150.0,
            proteinPer100g = 9.5,
            carbsPer100g = 5.0,
            fatPer100g = 10.5,
            fiberPer100g = 3.0
        ),
        FoodEntity(
            foodId = "paneer_butter_masala",
            name = "Paneer Butter Masala",
            category = "Curry",
            servingUnit = "bowl",
            defaultGrams = 240.0,
            caloriesPer100g = 195.0,
            proteinPer100g = 10.0,
            carbsPer100g = 7.0,
            fatPer100g = 14.0,
            fiberPer100g = 1.5
        ),
        FoodEntity(
            foodId = "poha",
            name = "Poha",
            category = "Breakfast",
            servingUnit = "plate",
            defaultGrams = 180.0,
            caloriesPer100g = 135.0,
            proteinPer100g = 3.0,
            carbsPer100g = 24.0,
            fatPer100g = 3.0,
            fiberPer100g = 2.0
        ),
        FoodEntity(
            foodId = "rasgulla",
            name = "Rasgulla",
            category = "Sweets",
            servingUnit = "piece",
            defaultGrams = 50.0,
            caloriesPer100g = 185.0,
            proteinPer100g = 4.0,
            carbsPer100g = 38.0,
            fatPer100g = 1.8,
            fiberPer100g = 0.2
        ),
        FoodEntity(
            foodId = "samosa",
            name = "Samosa",
            category = "Snacks",
            servingUnit = "piece",
            defaultGrams = 75.0,
            caloriesPer100g = 260.0,
            proteinPer100g = 4.5,
            carbsPer100g = 32.0,
            fatPer100g = 13.0,
            fiberPer100g = 2.5
        ),
        FoodEntity(
            foodId = "kachori",
            name = "Kachori",
            category = "Snacks",
            servingUnit = "piece",
            defaultGrams = 70.0,
            caloriesPer100g = 280.0,
            proteinPer100g = 5.0,
            carbsPer100g = 35.0,
            fatPer100g = 14.0,
            fiberPer100g = 2.0
        ),
        FoodEntity(
            foodId = "modak",
            name = "Modak",
            category = "Sweets",
            servingUnit = "piece",
            defaultGrams = 45.0,
            caloriesPer100g = 240.0,
            proteinPer100g = 3.0,
            carbsPer100g = 45.0,
            fatPer100g = 6.0,
            fiberPer100g = 1.5
        ),
        FoodEntity(
            foodId = "mysore_pak",
            name = "Mysore Pak",
            category = "Sweets",
            servingUnit = "piece",
            defaultGrams = 40.0,
            caloriesPer100g = 420.0,
            proteinPer100g = 4.0,
            carbsPer100g = 55.0,
            fatPer100g = 21.0,
            fiberPer100g = 1.0
        )
    )
}
